name: Publish Release

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Get previous tag
        run: echo "previous_tag=$(git rev-parse $(git describe --tags --abbrev=0 --exclude *-dev) 2>/dev/null || echo '')" >> $GITHUB_ENV

      - name: Build Changelog
        id: build_changelog
        uses: metcalfc/changelog-generator@v4.1.0
        if: env.previous_tag
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ github.ref }}
          base-ref: ${{ env.previous_tag }}
          fetch: false

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'mod_version'

      - name: Upload assets to releases
        run: |
          chmod +x gradlew
          ./gradlew build publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Publish to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 2xO4GAzs
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 904395
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: Just Let Me In ${{ steps.read_property.outputs.mod_version }}

          changelog: ${{steps.build_changelog.outputs.changelog}}

          version-type: release
          loaders: |
            forge
            neoforge

          game-versions: |
            >=1.18.2

          dependencies: |
            configured(recommended)

          java: |
            17